"""Checks for sync_skill_catalog.py: run `python check_sync_skill_catalog.py` (not named test_*, so unittest discovery skips it).

Written by the orchestrator, independently of the model that drafted the tool."""
import subprocess, sys, tempfile
from pathlib import Path

HEADER = (
    "# GENERATED from the lab's canonical catalog by sync_skill_catalog.py.\n"
    "# Do not edit this file. Edit the canonical catalog, run the sync tool, and commit both.\n"
    "# A drift check (--check) fails when this file and the canonical catalog differ.\n"
)
SRC = "schema_version: 1\nupdated: '2026-10-04'\nsources:\n  - id: crossref\n    access: api\n    base_url: https://api.crossref.org/\n"
cand = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).with_name("sync_skill_catalog.py")
results = []


def run(src: Path, dst: Path, *extra: str):
    p = subprocess.run([sys.executable, str(cand), "--source", str(src), "--target", str(dst), *extra], capture_output=True, text=True)
    return p.returncode, (p.stdout + p.stderr)


def case(name: str, ok: bool, detail: str = ""):
    results.append(ok)
    print(("PASS " if ok else "FAIL ") + name + ("" if ok else f"  ({detail})"))


with tempfile.TemporaryDirectory() as td:
    d = Path(td)
    src, dst = d / "canonical.yaml", d / "out" / "copy.yaml"
    src.write_text(SRC, encoding="utf-8", newline="\n")
    code, out = run(src, dst)
    got = dst.read_bytes().decode("utf-8") if dst.exists() else None
    case("write creates the target (and its parent folder) with exit 0", code == 0 and got is not None, f"exit={code} {out}")
    case("target = header + one blank line + the source text", got == HEADER + "\n" + SRC, repr(got)[:200])
    case("the output has only LF line endings", got is not None and "\r" not in got)
    if not dst.exists():  # keep later cases independent of earlier failures
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(HEADER + "\n" + SRC, encoding="utf-8", newline="\n")
    code, out = run(src, dst)
    case("a second run says already in sync, exit 0", code == 0 and "already in sync" in out, f"exit={code} {out}")
    code, out = run(src, dst, "--check")
    case("--check on an equal target: exit 0 and says in sync", code == 0 and "in sync" in out, f"exit={code} {out}")
    dst.write_text(dst.read_text(encoding="utf-8") + "# hand edit\n", encoding="utf-8", newline="\n")
    edited = dst.read_text(encoding="utf-8")
    code, out = run(src, dst, "--check")
    case("--check after a hand edit: exit 1 and says DRIFT", code == 1 and "DRIFT" in out, f"exit={code} {out}")
    case("--check never writes", dst.read_text(encoding="utf-8") == edited)
    code, out = run(src, dst)
    case("a plain run repairs the drift", code == 0 and dst.read_text(encoding="utf-8") == HEADER + "\n" + SRC, f"exit={code} {out}")
    code, out = run(src, d / "missing" / "nope.yaml", "--check")
    case("--check with a missing target: exit 1 and says missing", code == 1 and "missing" in out.lower(), f"exit={code} {out}")
    case("--check does not create the missing target", not (d / "missing").exists())
    bad = d / "bad.yaml"
    bad.write_text("just: a mapping\nwithout: sources\n", encoding="utf-8")
    t2 = d / "t2.yaml"
    code, out = run(bad, t2)
    case("a source without a sources list: exit 2 with an error line, target not created", code == 2 and "error:" in out and not t2.exists(), f"exit={code} {out}")
    code, out = run(d / "nope.yaml", t2)
    case("a missing source: exit 2, target not created", code == 2 and "error:" in out and not t2.exists(), f"exit={code} {out}")
    notmap = d / "list.yaml"
    notmap.write_text("- a\n- b\n", encoding="utf-8")
    code, out = run(notmap, t2)
    case("a source that is not a mapping: exit 2", code == 2, f"exit={code} {out}")
    crlf = d / "crlf.yaml"
    crlf.write_bytes(SRC.replace("\n", "\r\n").encode("utf-8"))
    t3 = d / "t3.yaml"
    code, out = run(crlf, t3)
    case("a CRLF source produces an LF-only target equal to the LF build", code == 0 and t3.exists() and t3.read_bytes().decode("utf-8") == HEADER + "\n" + SRC, f"exit={code} {out}")
    code, out = run(crlf, t3, "--check")
    case("--check against the CRLF source is in sync", code == 0, f"exit={code} {out}")
    hdr = d / "hdr.yaml"
    hdr.write_text(HEADER + "\n" + SRC, encoding="utf-8", newline="\n")
    t4 = d / "t4.yaml"
    code, out = run(hdr, t4)
    case("a source that already carries the header does not get any header line twice", code == 0 and t4.exists() and t4.read_text(encoding="utf-8") == HEADER + "\n" + SRC, f"exit={code} {t4.read_text(encoding='utf-8')[:300] if t4.exists() else out}")
    code, out = subprocess.run([sys.executable, str(cand)], capture_output=True, text=True).returncode, ""
    case("no arguments is a usage error (non-zero)", code != 0)

passed = sum(results)
print(f"{passed}/{len(results)} passed")
sys.exit(0 if passed == len(results) else 1)
