#!/usr/bin/env python3
"""Keep a generated copy of a YAML catalog in sync with the canonical one."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

HEADER = (
    "# GENERATED from the lab's canonical catalog by sync_skill_catalog.py.\n"
    "# Do not edit this file. Edit the canonical catalog, run the sync tool, and commit both.\n"
    "# A drift check (--check) fails when this file and the canonical catalog differ.\n"
)


def fail(msg: str) -> None:
    print(f"error: {msg}")
    sys.exit(2)


def strip_existing_header(text: str) -> str:
    """Remove the whole generated header (all its lines) and the one blank line after it."""
    if not text.startswith(HEADER):
        return text
    text = text[len(HEADER):]
    return text[1:] if text.startswith("\n") else text


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--target", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    src_path: Path = args.source
    dst_path: Path = args.target

    if not src_path.is_file():
        fail(f"source file {src_path} is missing")

    try:
        raw_bytes = src_path.read_bytes()
    except Exception as exc:  # pragma: no cover - unexpected IO errors
        fail(f"could not read source: {exc}")

    try:
        text = raw_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        fail(f"source is not valid UTF-8: {exc}")

    text = text.replace("\r\n", "\n")

    data = yaml.safe_load(text)
    if not isinstance(data, dict) or "sources" not in data or not isinstance(data["sources"], list):
        fail("source is not a YAML mapping with a 'sources' list")

    body = strip_existing_header(text)
    expected = HEADER + "\n" + body

    if args.check:
        if not dst_path.is_file():
            print("DRIFT: target is missing")
            sys.exit(1)
        try:
            current_bytes = dst_path.read_bytes()
        except Exception as exc:  # pragma: no cover
            fail(f"could not read target: {exc}")
        try:
            current = current_bytes.decode("utf-8").replace("\r\n", "\n")
        except UnicodeDecodeError as exc:
            print("DRIFT: target differs from the canonical catalog")
            sys.exit(1)
        if current != expected:
            print("DRIFT: target differs from the canonical catalog")
            sys.exit(1)
        print("in sync")
        return

    if dst_path.is_file():
        try:
            existing_bytes = dst_path.read_bytes()
        except Exception as exc:  # pragma: no cover
            fail(f"could not read target: {exc}")
        try:
            existing = existing_bytes.decode("utf-8").replace("\r\n", "\n")
        except UnicodeDecodeError:
            existing = None
        if existing == expected:
            print("already in sync")
            return

    try:
        dst_path.parent.mkdir(parents=True, exist_ok=True)
        with open(dst_path, "wb") as f:
            f.write(expected.encode("utf-8"))
    except Exception as exc:  # pragma: no cover
        fail(f"could not write target: {exc}")
    print(f"wrote {dst_path}")


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as exc:
        print(f"error: {exc}")
        sys.exit(2)
