"""Build web/cftr-data.js: C-alpha traces of four human CFTR structures, superposed on one of them, plus the part boundaries from UniProt.

Reads only files that tools/sources/fetch_sources.py has already downloaded (see README.md in this folder); it makes no network request. Everything it writes comes from those files:
the title, method, resolution, deposition date and paper of each entry, the C-alpha atoms of chain A (model 1), the ligand names, and UniProt's
domain and region annotations and sequence length. Nothing is typed in except the list of entry ids.

Each structure also records how its own sequence differs from UniProt's, exactly as the file declares it (an engineered mutation, a deletion, expression-tag
residues), and the build refuses to continue if a placed residue disagrees with UniProt's sequence without the file saying so.
The "uniprot" block carries what the page lets researchers look at: the sequence, the annotated natural variants, transmembrane segments, topology, ATP-binding sites,
and UniProt's helix, strand and turn ranges ("secondary"), which the page draws as wider bands. Those ranges are UniProt's annotation (its evidence is other
PDB entries, kept as ids); nothing here computes secondary structure from the four models' coordinates.

Structures are superposed on the first one (6MSM) using the C-alpha atoms of the membrane-spanning parts that both files place at the same residue
number with the same residue type. The superposition is Horn's quaternion method with a Jacobi eigen-solver, so only the standard library is needed;
tests/test_data.py proves it recovers a known rotation.

Usage: python tools/cftr-model/build_traces.py [--inputs DIR] [--out PATH]
       DIR holds 6MSM.cif.gz 5UAK.cif.gz 8EIQ.cif.gz 8EJ1.cif.gz and p13569.json (default: sources/downloads, which is git-ignored and filled by tools/sources/fetch_sources.py)."""
import argparse
import gzip
import json
import math
import shlex
from pathlib import Path

HERE = Path(__file__).resolve().parent                  # tools/cftr-model
ROOT = HERE.parents[1]                                  # the repository root
IDS = ["6MSM", "5UAK", "8EIQ", "8EJ1"]          # the reference first: the others are moved onto it
DEFAULT_OUT = HERE / "web" / "cftr-data.js"
DEFAULT_INPUTS = ROOT / "sources" / "downloads"      # where tools/sources/fetch_sources.py puts the catalog entries rcsb-pdb-* and uniprot-p13569
HEADER = "// Generated by tools/cftr-model/build_traces.py from RCSB PDB files (CC0) and UniProt P13569. Do not edit by hand.\r\n"
WANTED = {"_struct.title": "title", "_exptl.method": "method", "_em_3d_reconstruction.resolution": "resolution_A",
          "_pdbx_database_status.recvd_initial_deposition_date": "deposited", "_citation.title": "paper",
          "_citation.journal_abbrev": "journal", "_citation.year": "paper_year", "_citation.pdbx_database_id_PubMed": "pubmed"}


def read_cif(path):
    lines = gzip.open(path, "rt", encoding="utf-8").read().splitlines()
    cols, rows, started = [], [], False
    for ln in lines:
        if ln.startswith("_atom_site."):
            cols.append(ln.strip()[len("_atom_site."):]); started = True
        elif started and ln.startswith(("ATOM", "HETATM")):
            rows.append(ln.split())
        elif started and rows and not ln.startswith(("ATOM", "HETATM")):
            break
    ix = {c: i for i, c in enumerate(cols)}
    meta = {}
    for k_i, ln in enumerate(lines):
        for k, name in WANTED.items():
            if ln.startswith(k + " ") and name not in meta:
                v = ln[len(k):].strip()
                if not v and lines[k_i + 1].startswith(";"):            # a multi-line value: text between two lines that start with ";"
                    parts, j = [lines[k_i + 1][1:].strip()], k_i + 2
                    while j < len(lines) and not lines[j].startswith(";"):
                        parts.append(lines[j].strip())
                        j += 1
                    v = " ".join(p for p in parts if p)
                meta[name] = v.strip("'")
    differences, tags = read_differences(lines)
    meta["differences"] = differences
    meta["expression_tag_residues"] = tags
    ca, ligands = {}, {}
    for r in rows:
        if r[ix["pdbx_PDB_model_num"]] != "1":
            continue
        if r[ix["group_PDB"]] == "HETATM":
            c = r[ix["label_comp_id"]]
            ligands[c] = ligands.get(c, 0) + 1
        elif r[ix["label_atom_id"]] == "CA" and r[ix["auth_asym_id"]] == "A":
            ca[int(r[ix["auth_seq_id"]])] = (r[ix["label_comp_id"]], [float(r[ix["Cartn_x"]]), float(r[ix["Cartn_y"]]), float(r[ix["Cartn_z"]])])
    return meta, ca, ligands


def read_differences(lines):
    """The file's own list of where its sequence differs from UniProt's (_struct_ref_seq_dif). Expression-tag residues are only counted."""
    cols, i = [], 0
    while i < len(lines) and not lines[i].startswith("_struct_ref_seq_dif."):
        i += 1
    while i < len(lines) and lines[i].startswith("_struct_ref_seq_dif."):
        cols.append(lines[i].strip()[len("_struct_ref_seq_dif."):])
        i += 1
    out, tags = [], 0
    while cols and i < len(lines) and not lines[i].startswith(("#", "_", "loop_")):
        row = dict(zip(cols, shlex.split(lines[i])))
        i += 1
        if row.get("details") == "expression tag":
            tags += 1
            continue
        pos = row.get("pdbx_seq_db_seq_num", "?")
        out.append({"position": int(pos) if pos.isdigit() else None, "file_residue": None if row["mon_id"] == "?" else row["mon_id"],
                    "uniprot_residue": None if row["db_mon_id"] == "?" else row["db_mon_id"], "details": row["details"]})
    return out, tags


THREE = {"ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C", "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "ILE": "I", "LEU": "L", "LYS": "K", "MET": "M",
         "PHE": "F", "PRO": "P", "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V"}


def mean(pts):
    n = len(pts)
    return [sum(p[k] for p in pts) / n for k in range(3)]


def jacobi_eigen(a, sweeps=60):
    """Eigenvalues and eigenvectors (as columns) of a small symmetric matrix given as a list of lists."""
    n = len(a)
    a = [row[:] for row in a]
    v = [[1.0 if i == j else 0.0 for j in range(n)] for i in range(n)]
    for _ in range(sweeps):
        off = sum(a[i][j] ** 2 for i in range(n) for j in range(i + 1, n))
        if off < 1e-18:
            break
        for p in range(n):
            for q in range(p + 1, n):
                if abs(a[p][q]) < 1e-300:
                    continue
                theta = (a[q][q] - a[p][p]) / (2 * a[p][q])
                t = (1.0 if theta >= 0 else -1.0) / (abs(theta) + math.sqrt(theta * theta + 1))
                c = 1 / math.sqrt(t * t + 1); s = t * c
                for k in range(n):
                    akp, akq = a[k][p], a[k][q]
                    a[k][p], a[k][q] = c * akp - s * akq, s * akp + c * akq
                for k in range(n):
                    apk, aqk = a[p][k], a[q][k]
                    a[p][k], a[q][k] = c * apk - s * aqk, s * apk + c * aqk
                for k in range(n):
                    vkp, vkq = v[k][p], v[k][q]
                    v[k][p], v[k][q] = c * vkp - s * vkq, s * vkp + c * vkq
    return [a[i][i] for i in range(n)], v


def superpose(P, Q):
    """Rotation matrix R (3x3) and shift t so that R*p + t best matches q in the least-squares sense (Horn 1987)."""
    pc, qc = mean(P), mean(Q)
    S = [[0.0] * 3 for _ in range(3)]
    for p, q in zip(P, Q):
        for i in range(3):
            for j in range(3):
                S[i][j] += (p[i] - pc[i]) * (q[j] - qc[j])
    Sxx, Sxy, Sxz, Syx, Syy, Syz, Szx, Szy, Szz = S[0][0], S[0][1], S[0][2], S[1][0], S[1][1], S[1][2], S[2][0], S[2][1], S[2][2]
    N = [[Sxx + Syy + Szz, Syz - Szy, Szx - Sxz, Sxy - Syx],
         [Syz - Szy, Sxx - Syy - Szz, Sxy + Syx, Szx + Sxz],
         [Szx - Sxz, Sxy + Syx, -Sxx + Syy - Szz, Syz + Szy],
         [Sxy - Syx, Szx + Sxz, Syz + Szy, -Sxx - Syy + Szz]]
    vals, vecs = jacobi_eigen(N)
    k = max(range(4), key=lambda i: vals[i])
    q0, q1, q2, q3 = (vecs[r][k] for r in range(4))
    R = [[q0 * q0 + q1 * q1 - q2 * q2 - q3 * q3, 2 * (q1 * q2 - q0 * q3), 2 * (q1 * q3 + q0 * q2)],
         [2 * (q1 * q2 + q0 * q3), q0 * q0 - q1 * q1 + q2 * q2 - q3 * q3, 2 * (q2 * q3 - q0 * q1)],
         [2 * (q1 * q3 - q0 * q2), 2 * (q2 * q3 + q0 * q1), q0 * q0 - q1 * q1 - q2 * q2 + q3 * q3]]
    t = [qc[i] - sum(R[i][j] * pc[j] for j in range(3)) for i in range(3)]
    return R, t


def apply(R, t, p):
    return [sum(R[i][j] * p[j] for j in range(3)) + t[i] for i in range(3)]


def shared_residues(ca, ref, ranges):
    """Residue numbers used to fit a structure onto the reference: placed in both, the same amino acid in both, inside one of the given (first, last) ranges."""
    return sorted(n for n in ca if n in ref and any(a <= n <= b for a, b in ranges) and ca[n][0] == ref[n][0])


def uniprot_parts(path):
    j = json.loads(Path(path).read_text(encoding="utf-8"))
    out = []
    for f in j["features"]:
        if f["type"] == "Domain" or (f["type"] == "Region" and "isordered" in f.get("description", "")):
            out.append({"type": f["type"], "name": f["description"], "start": f["location"]["start"]["value"], "end": f["location"]["end"]["value"]})
    return out, j["sequence"]["length"]


SECONDARY_TYPES = {"Helix": "helix", "Beta strand": "strand", "Turn": "turn"}      # UniProt's secondary-structure feature types, and the short names the page uses


def secondary_structure(feats):
    """UniProt's own 'Helix', 'Beta strand' and 'Turn' ranges, in chain order. UniProt derives them from PDB entries (its evidence is a PDB id, which is
    kept); the page draws them as wider bands. They are an annotation of the sequence, not something computed here from the four models' coordinates."""
    out = []
    for f in feats:
        kind = SECONDARY_TYPES.get(f["type"])
        if kind is None:
            continue
        start, end = f["location"]["start"]["value"], f["location"]["end"]["value"]
        if not (isinstance(start, int) and isinstance(end, int) and 1 <= start <= end):
            raise SystemExit(f"UniProt {f['type']} feature with an unusable range: {f['location']}")
        out.append({"type": kind, "start": start, "end": end, "evidence": sorted({e["id"] for e in f.get("evidences", []) if e.get("source") == "PDB" and e.get("id")})})
    out.sort(key=lambda s: (s["start"], s["end"]))
    for a, b in zip(out, out[1:]):
        if b["start"] <= a["end"]:
            raise SystemExit(f"UniProt secondary-structure ranges overlap: {a} and {b}")
    return out


def uniprot_block(path):
    j = json.loads(Path(path).read_text(encoding="utf-8"))
    feats = j["features"]
    span = lambda f: {"start": f["location"]["start"]["value"], "end": f["location"]["end"]["value"]}
    variants = []
    for f in feats:
        if f["type"] != "Natural variant":
            continue
        alt = f.get("alternativeSequence", {})
        variants.append({"id": f["featureId"], **span(f), "from": alt.get("originalSequence"), "to": alt.get("alternativeSequences", []), "description": f.get("description", ""),
                         "evidence": [e["id"] for e in f.get("evidences", []) if e.get("source") == "PubMed"]})
    return {"accession": j["primaryAccession"], "entry_version": j["entryAudit"]["entryVersion"], "last_annotation_update": j["entryAudit"]["lastAnnotationUpdateDate"],
            "sequence": j["sequence"]["value"],
            "transmembrane": [{**span(f), "name": f.get("description", "")} for f in feats if f["type"] == "Transmembrane"],
            "topology": [{**span(f), "name": f.get("description", "")} for f in feats if f["type"] == "Topological domain"],
            "atp_sites": [span(f) for f in feats if f["type"] == "Binding site" and "ATP" in f.get("ligand", {}).get("name", "")],
            "secondary": secondary_structure(feats),
            "variants": variants}


def check_against_sequence(sid, ca, differences, sequence):
    """Every placed residue must be the amino acid UniProt has at that number, unless the file itself says it was changed there."""
    declared = {d["position"] for d in differences if d["position"] is not None}
    bad = [(n, name) for n, (name, _) in ca.items() if THREE.get(name) != sequence[n - 1] and n not in declared]
    if bad:
        raise SystemExit(f"{sid}: residues that differ from the UniProt sequence without the file declaring it: {bad[:5]}")


def build(inputs):
    inputs = Path(inputs)
    domains, length = uniprot_parts(inputs / "p13569.json")
    tmds = [(d["start"], d["end"]) for d in domains if "transmembrane" in d["name"].lower()]
    parsed = {i: read_cif(inputs / f"{i}.cif.gz") for i in IDS}
    ref = parsed[IDS[0]][1]
    centre = None
    uniprot = uniprot_block(inputs / "p13569.json")
    out = {"source": "RCSB PDB mmCIF (CC0 1.0), UniProt P13569; C-alpha atoms of chain A, model 1, superposed on 6MSM", "domains": domains, "length": length,
           "numbering": "author residue numbers of the PDB entries, which equal UniProt P13569 numbering (checked residue by residue against the UniProt sequence)",
           "uniprot": uniprot, "structures": []}
    for i in IDS:
        meta, ca, ligands = parsed[i]
        check_against_sequence(i, ca, meta["differences"], uniprot["sequence"])
        shared = shared_residues(ca, ref, tmds)
        R, t = superpose([ca[n][1] for n in shared], [ref[n][1] for n in shared])
        moved = {n: (v[0], apply(R, t, v[1])) for n, v in ca.items()}
        rmsd = math.sqrt(sum(sum((a - b) ** 2 for a, b in zip(moved[n][1], ref[n][1])) for n in shared) / len(shared))
        if centre is None:
            centre = mean([v[1] for v in moved.values()])
        nums = sorted(moved)
        segs, cur = [], [nums[0]]
        for n in nums[1:]:
            if n == cur[-1] + 1:
                cur.append(n)
            else:
                segs.append(cur); cur = [n]
        segs.append(cur)
        rel = lambda n: [round(moved[n][1][k] - centre[k], 1) for k in range(3)]
        seg_out = [{"start": s[0], "xyz": [c for n in s for c in rel(n)]} for s in segs]
        out["structures"].append({"id": i, **meta, "residues_traced": len(nums), "first": nums[0], "last": nums[-1], "segments": seg_out,
                                  "res508": {"name": moved[508][0], "xyz": rel(508)} if 508 in moved else None,
                                  "ligand_components": sorted(ligands), "superposed_on": IDS[0], "superposition_residues": len(shared), "superposition_rmsd_A": round(rmsd, 2)})
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--inputs", default=str(DEFAULT_INPUTS))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    a = ap.parse_args(argv)
    data = build(a.inputs)
    Path(a.out).write_bytes((HEADER + "export default " + json.dumps(data, separators=(",", ":")) + ";\r\n").encode("utf-8"))
    for s in data["structures"]:
        print(f"{s['id']}: {s['residues_traced']} of {data['length']} residues placed; superposed on {s['superposition_residues']} membrane-spanning residues, {s['superposition_rmsd_A']:.2f} A; residue 508: {s['res508'] and s['res508']['name']}")
    print("wrote", a.out)


if __name__ == "__main__":
    main()
